do not pass proxy env variables by tox
In an environment where http_proxy env variable is needed to buil a
proper python virtualenv the functional test fails with:
RuntimeError: http_proxy or https_proxy set in environment, please unset

This patch removes passing proxy env varibles in tox.ini to avoid this
error.

Change-Id: Ia4d8fe952aecb5c3e688878ef0fdafd6fac4fc7a
Closes-Bug: #1706545